import sys
import time
from pathlib import Path

sys.path.append(str(Path(__file__).parent))

from test_auth import run_tests as run_phase1_tests
from test_encryption import run_encryption_tests as run_phase2_tests
from test_crud import run_crud_tests as run_phase3_tests
from pw_util import calculate_password_strength, generate_secure_password

def run_phase4_tests():
    print("=" * 65)
    print("⚡ RUNNING PHASE 4 UTILITIES & PASSWORD GENERATOR TESTS")
    print("=" * 65)

    # 1. Test Password Generator Length & Variety
    gen_pw_16 = generate_secure_password(length=16)
    assert len(gen_pw_16) == 16, f"Expected password length 16, got {len(gen_pw_16)}"
    
    analysis_16 = calculate_password_strength(gen_pw_16)
    assert analysis_16["score"] >= 3, "Generated 16-char password should be Strong or Very Strong!"
    print(f"✅ 1. Generated 16-char Password: '{gen_pw_16}'")
    print(f"   Strength Score: {analysis_16['score']}/4 ({analysis_16['label']}, {analysis_16['entropy']} bits entropy)")

    # 2. Test CSPRNG Uniqueness Across 1000 Generations
    generated_set = {generate_secure_password(16) for _ in range(1000)}
    assert len(generated_set) == 1000, "CRITICAL: Duplicate passwords generated by CSPRNG!"
    print("✅ 2. CSPRNG Randomness Verified (1,000 unique passwords generated with zero collisions).")

    # 3. Test Strength Meter Calculations
    weak_pw = "12345"
    weak_analysis = calculate_password_strength(weak_pw)
    assert weak_analysis["score"] == 0, f"Expected weak score 0, got {weak_analysis['score']}"
    assert weak_analysis["label"] == "Very Weak"

    strong_pw = "K#9x!mQ2$pL7*vT1"
    strong_analysis = calculate_password_strength(strong_pw)
    assert strong_analysis["score"] == 4, f"Expected strong score 4, got {strong_analysis['score']}"
    assert strong_analysis["label"] == "Very Strong"

    print("✅ 3. Password Strength Meter scoring verified (Weak -> 0, Complex -> 4).")

    print("=" * 65)
    print("🎉 ALL PHASE 4 UTILITIES TESTS PASSED PERFECTLY!")
    print("=" * 65)


def run_master_test_suite():
    print("\n" + "🚀" * 30)
    print("      SECURE PASSWORD MANAGER — MASTER END-TO-END TEST SUITE")
    print("🚀" * 30 + "\n")

    start_time = time.time()

    try:
        # Phase 1
        run_phase1_tests()
        print("\n")

        # Phase 2
        run_phase2_tests()
        print("\n")

        # Phase 3
        run_phase3_tests()
        print("\n")

        # Phase 4
        run_phase4_tests()
        print("\n")

        elapsed = round(time.time() - start_time, 2)
        print("🌟" * 35)
        print(f"  ALL PHASES (1, 2, 3, 4) PASSED 100% SUCCESSFULLY IN {elapsed}s!")
        print("  THE SECURE PASSWORD MANAGER BACKEND & VAULT CORE IS FULLY VERIFIED.")
        print("🌟" * 35 + "\n")

    except Exception as e:
        print("\n" + "❌" * 30)
        print(f"  TEST SUITE FAILED AT PHASE: {e}")
        print("❌" * 30 + "\n")
        sys.exit(1)

if __name__ == "__main__":
    run_master_test_suite()
